name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Docker Build
      run: |
        docker build --platform=linux/arm/v7 -f Dockerfile-armv7 -t device_bridge_arm_build .
        docker run -d --name device_bridge_arm_build device_bridge_arm_build bash
        docker cp device_bridge_arm_build:/opt/build/docker-pull ./docker-pull
        docker rm -f device_bridge_arm_build
        docker rmi -f device_bridge_arm_build
    - name: Prepare Release
      id: prepare_release
      run: |
        VERSION=$(cat VERSION)
        echo ::set-output name=version::$VERSION
    - name: Get latest release info
      id: get_release_info
      run: |
        LATEST_RELEASE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases/latest)
        echo "::set-output name=upload_url::$(echo $LATEST_RELEASE | jq -r '.upload_url')"
        echo "::set-output name=tag_name::$(echo $LATEST_RELEASE | jq -r '.tag_name')"
    - name: Upload Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}"
        asset_path: ./docker-pull
        asset_name: docker-pull
        asset_content_type: application/octet-stream
