# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: go_build

on:
  push:
    branches: [ "release" ]


jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.21'
      - name: Prepare Release
        id: prepare_release
        run: |
          VERSION=$(cat VERSION)
          echo ::set-output name=version::$VERSION
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.prepare_release.outputs.version }}
          release_name: Release ${{ steps.prepare_release.outputs.version }}
      - name: Save release ID
        run: echo "${{ steps.create_release.outputs.id }}" > release_id.txt
      - name: Upload release ID
        uses: actions/upload-artifact@v2
        with:
          name: release_id
          path: release_id.txt
    
  build_linux:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.21'
    - name: Build
      run: cd ./core && go build -o ../docker-pull .
    - name: Prepare Release
      id: prepare_release
      run: |
        VERSION=$(cat VERSION)
        echo ::set-output name=version::$VERSION
    
    - name: Download release ID
      uses: actions/download-artifact@v2
      with:
        name: release_id
    - name: Read release ID
      id: release_id
      run: echo "::set-output name=id::$(cat release_id/release_id.txt)"
      
    - name: Upload Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://api.github.com/repos/${{ github.repository }}/releases/${{ steps.release_id.outputs.id }}
        asset_path: ./docker-pull
        asset_name: docker-pull
        asset_content_type: application/octet-stream

  build_windows:
    runs-on: windows-latest
    permissions: write-all
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.21'
    - name: Build
      run: |
        cd .\core
        go build -o ..\docker-pull.exe .
    - name: Prepare Release
      id: prepare_release
      run: |
        $VERSION = Get-Content -Path .\VERSION
        Write-Output "::set-output name=version::$VERSION"
    - name: Upload Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.vars.upload_url }}
        asset_path: .\docker-pull.exe
        asset_name: docker-pull.exe
        asset_content_type: application/octet-stream
